export { default as Logo } from "./Vinc.jpg"  
export { default as Kitchen } from "./kitchen.jpg"
export { default as Light } from "./light.jpg"
export { default as Sensor } from "./lightwithsensor.jpg"
export { default as Panel } from "./panel.jpg"
export { default as Solar } from "./solar.jpg"
export { default as Solar2 } from "./solar112.png"
export {default as Pannel} from "./pannel.jpg"