export { default as Logo } from "./Vinc.jpg"  
export { default as Kitchen } from "./kitchen.jpg"
export { default as Light } from "./light.jpg"
export { default as Sensor } from "./lightwithsensor.jpg"
export { default as Panel } from "./panel.jpg"
export { default as Solar } from "./solar.jpg"
export { default as Solar2 } from "./solar112.png"
export { default as Pannel } from "./pannel.jpg"
export { default as image1 } from "./image1.jpeg"
export { default as image2 } from "./image2.jpeg"
export { default as image3 } from "./image3.jpeg"
export { default as image4 } from "./image4.jpeg"
export { default as image5 } from "./image5.jpeg"
export { default as image6 } from "./image6.jpeg"
export { default as image7 } from "./image7.jpeg"

